fis:
  ftp:
    host: localhost
    path: ./
    username: ftp
    password: ftp
    pollInterval: 1000
  weather:
    key: a012345678901234567890123456789b
  operation:
    duration: 5000
  client:
    weatherPollInterval: 60000
    operationPollInterval: 500
    highlight: foo
server:
  port: 8080
