fis:
  ftp:
    host: fritz.box
    path: /FRITZ/faxbox
    fileSuffix: .pdf
    pollInterval: 10000
  tesseract:
    lang: deu
  weather:
    lang: de
    units: metric
    location: 2921044
    pollInterval: 60000
  operation:
    duration: 1800000
  client:
    weatherPollInterval: 30000
    operationPollInterval: 2000
    highlight: ""

logging:
  pattern:
    console:
  file:
    name: fis.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/fis-%d{yyyy-MM-dd}.%i.log
      max-history: 30
