fis:
  ftp:
    host: fritz.box
    path: /FRITZ/faxbox
    fileSuffix: .pdf
    pollInterval: 5000
    checkUploadCompleteInterval: 300
    checkUploadCompleteMaxAttempts: 10
    maxFileSize: 10000000
  tesseract:
    lang: deu
  weather:
    lang: de
    units: metric
    location: 2921044
    pollInterval: 60000
  operation:
    duration: 1800000
    notifications:
      senderName: JarFIS
      smsLimit: 10 # per day per recipient
  client:
    weatherPollInterval: 30000
    operationPollInterval: 2000
    highlight: