fis:
  ftp:
    # username: SECRET
    # password: SECRET
    host: fritz.box
    path: /FRITZ/faxbox
    fileSuffix: .pdf
    pollInterval: 5000
    checkUploadCompleteInterval: 300
    checkUploadCompleteMaxAttempts: 10
    maxFileSize: 10000000
  tesseract:
    lang: deu
    tessdata: # CUSTOM TESSDATA
  weather:
    key: # OPENWEATHERMAP API KEY
    lang: de
    units: metric
    location: 2921044
    pollInterval: 60000
  operation:
    duration: 1800000
    origin: # LOCATION OF YOUR FIRE STATION
    notification:
      senderName: JarFIS
      senderMail: # TO AVOID JUNK FOLDER
      smsLimit: 10 # PER DAY PER RECIPIENT TO AVOID COSTS BY SPAMMERS
      mail:
      # - foo@example.com
      sms:
      # - 0123456789
  client:
    weatherPollInterval: 30000
    operationPollInterval: 2000
    highlight: # YOUR FIRE STATION NAME